pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount: [ '/drone/docker', '/root/.ssh' ]
    volumes: [ '/tmp/cache:/cache' ]

  preset:
    image: shynome/alpine-drone-ci:dev
    deploy: ssh set
    secrets: [ ssh_key ]
    ssh_conf: |
      Host manager
        User root
        HostName 173.254.200.81
        StrictHostKeyChecking no

  publish:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: shynome/alpine-drone-ci-web-test
    dockerfile: docker/Dockerfile
    tags: 
      - ${DRONE_COMMIT_SHA}
      - latest
    storage_path: /drone/docker

  deploy:
    image: shynome/alpine-drone-ci:dev
    commands:
    - ls /root/.ssh/
    - ls ~/.ssh/
    - deploy docker to manager m_web shynome/alpine-drone-ci-web-test:$DRONE_COMMIT_SHA

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount: [ '/drone/docker', '/root/.ssh' ]
    volumes: [ '/tmp/cache:/cache' ]

