
pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount: [ '/drone/docker', '/drone/.ssh' ]
    volumes: [ '/tmp/cache:/cache' ]

  sss:
    image: shynome/alpine-drone-ci:dev
    storage_path: /drone/.ssh
    deploy: run "mkdir -p /drone/.ssh/ && echo '666'>/drone/.ssh/config"

  # preset:
  #   image: shynome/alpine-drone-ci:dev
  #   deploy: ssh set
  #   storage_path: /drone/.ssh
  #   secrets: [ ssh_key ]
  #   ssh_conf: |
  #     Host manager
  #       User root
  #       HostName 173.254.200.81
  #       StrictHostKeyChecking no

  publish:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: shynome/alpine-drone-ci-web-test
    dockerfile: docker/Dockerfile
    tags: [ '${DRONE_COMMIT_SHA}', latest ]
    storage_path: /drone/docker
  
  check: &check
    image: shynome/alpine-drone-ci:dev
    commands:
    - ls /drone/docker /drone/.ssh
  
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount: [ '/drone/docker', '/drone/.ssh' ]
    volumes: [ '/tmp/cache:/cache' ]

  check3:
    <<: *check

  deploy:
    image: shynome/alpine-drone-ci:dev
    commands:
    - ls /drone/docker
    - ls ~/.ssh/
    # - deploy docker to manager m_web shynome/alpine-drone-ci-web-test:$DRONE_COMMIT_SHA



