ssh_conf: &ssh_conf
  image: shynome/alpine-drone-ci:dev
  secrets: [ ssh_key ]
  ssh_conf: |
    Host manager
      User root
      HostName 173.254.200.81
      StrictHostKeyChecking no

pipeline:

  cmd:
    image: shynome/alpine-drone-ci
    commands:
      - exit 0


services:
  when: { branch: master }
  nginx:
    image: shynome/alpine-drone-ci
    environment:
      deploy: run 'echo $DRONE_COMMIT_SHA'

