ssh_conf: &ssh_conf
  image: shynome/alpine-drone-ci:dev
  secrets: [ ssh_key ]
  ssh_conf: |
    Host manager
      User root
      HostName 173.254.200.81
      StrictHostKeyChecking no

pipeline:

  cmd:
    image: shynome/alpine-drone-ci
    commands:
      - sleep 5s
      - curl nginx/.drone.yml


services:
  nginx:
    image: nginx:stable-alpine
